name: release
on:
  push:
    branches:
    - release**
  pull_request:
    branches:
    - release**
jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4.1.1
    - name: Set up python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.11'
    - name: Cache dependencies
      uses: actions/cache@v4.0.2
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-integration
    - name: Install pip dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install .[tests]
        pip cache purge
    - name: List pip dependencies
      run: pip list
    - name: Run integration checks
      run: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true